### ISSUE TITLE
Can you install ffmpeg from mc3man's repo instead?

### ISSUE THREAD

**Issue by dprus** [linuxserver/docker-beets#1]
https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media

It's much newer (2.8.1 vs 2.4.3 at the time of writing this) and has AAC support through libfdk_aac which, IMHO, is far superior. A lot of other components like lame are also a lot newer / more up-to-date.

Thanks.

**Comment by smdion** [comment]
I'll test and try it out.

**Comment by smdion** [comment]
Repo changed to mc3man

**Comment by dprus** [comment]
Awesome. Thanks!

**Comment by epatch** [comment]
Question: How do I designate it to use libfdk_aac instead of aac?  I try changeing -acodec to libfdk_aac instead of aac and it doesn't change anything.

**Comment by epatch** [comment]
It doesn't appear to have libfdk_aac enabled:

sudo docker exec -it beets /bin/bash -c 'ffmpeg'

ffmpeg version 3.2.6 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (Alpine 6.3.0)
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libmp3lame --enable-librtmp --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-x11grab --disable-stripping --disable-static --enable-vaapi --enable-libopus --disable-debug
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
