### ISSUE TITLE
[BUG] <Container is not working>

### ISSUE THREAD

**Issue by wiebereu** [linuxserver/docker-beets#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Is the second time that i installed the Beets container but after installation i see no information on the webpage. 
The only thing i see is Beets in the left upper corner of the screen but no further infomation. 
![beets](https://github.com/linuxserver/docker-beets/assets/58167538/d7a33647-8417-47a5-ae0a-43be460a78c5)

Take a look and you will see. 
The logs tells me nothing
[Beets-log.txt](https://github.com/linuxserver/docker-beets/files/11900833/Beets-log.txt)

### Expected Behavior

A GUI which i use. 

### Steps To Reproduce

No steps at the moment

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
Portainer
```

### Container logs

```bash
see attachment
```

**Comment by j0nnymoe** [comment]
That is the expected webui for beets.

**Comment by wiebereu** [comment]
> 

Yes but what can i do with an empty webui? You can't click on anything on this page
How can i start with a scan of my library if there is nothing to see in the webui?

**Comment by thespad** [comment]
Beets is primarily a CLI tool, I would suggest reading the documentation.

**Comment by wiebereu** [comment]
> Beets is primarily a CLI tool, I would suggest reading the documentation.

I don't want to be rude but i can say the same to you cause the version i installed says it worked with a webui. So i have read the documentation. 

Here is the link about Beets. [https://beets.io/](url)

Why do i need a webui if i have to do everything from the command line? It doesn't make sense

**Comment by thespad** [comment]
> The web plugin is a very basic alternative interface to beets that supplements the CLI. It can’t do much right now, and the interface is a little clunky, but you can use it to query and browse your music and—in browsers that support HTML5 Audio—you can even play music.

https://beets.readthedocs.io/en/stable/plugins/web.html

**Comment by j0nnymoe** [comment]
We also state here: https://github.com/linuxserver/docker-beets#application-setup how to use the container.

As Spad has linked the webui plugin, it's just used for querying the beets database and basic playback.
