### ISSUE TITLE
[BUG] ANTIALIAS was removed in Pillow 10.0.0

### ISSUE THREAD

**Issue by samcro1967** [linuxserver/docker-beets#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Beet import fails for some albums with the following error message:
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

Downgrading pillow to 9.5.0 resolves the issue.

### Expected Behavior

Beet import is successful.

### Steps To Reproduce

beet import /music/artist/album_title

### Environment

```markdown
- OS:  Ubuntu 22.04
- How docker service was installed:  Docker Compose
```

### CPU architecture

x86-64

### Docker creation

```bash
beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    restart: always
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8337:8337
    volumes:
      - ${docker}/beets:/config
      - ${downloads}:/downloads
      - ${xbmc}/Music/Managed:/music
```

### Container logs

```bash
N/A as container starts and runs successfully.  No errors are present in the container logs.
```

**Comment by somagaze** [comment]
I can reproduce, too. Downgrading pillow to 9.5.0 solves the issue for me, too.

**Comment by thespad** [comment]
This should have been resolved by https://github.com/linuxserver/docker-beets/pull/103
