### ISSUE TITLE
[BUG] Serving media files via Web UI

### ISSUE THREAD

**Issue by PBXg33k** [linuxserver/docker-beets#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm getting 500 error whenever i try to download/stream media files using the web ui.

I would expect that i would be served the media file, but instead there seems to occur a `TypeError` somewhere in beets.

I've looked at the Beets repository and it looks like they have updated their code, but i'm not sure if this has been picked up in these images as the error does still refer to `attachment_filename` in the error.

https://github.com/beetbox/beets/blob/master/beetsplug/web/__init__.py#L330

### Expected Behavior

Download or be able to stream media files

### Steps To Reproduce

1. Create new docker container (or compose) from the template provided by LSIO
2. Ingest a working media file
3. Open the web-ui
4. Play or download media from browser

### Environment

```markdown
- OS: Debian 11
- How docker service was installed: `piping https://get.docker.com/ through bash`


- OS: MacOS
- How docker service was installed: Official Docker package
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config:/config
      - ./library:/music
      - ./ingest:/downloads
    ports:
      - 8337:8337
    restart: unless-stopped
```

### Container logs

```bash
10.1.100.167 - - [31/Aug/2023 16:03:36] "GET / HTTP/1.1" 200 -
10.1.100.167 - - [31/Aug/2023 16:03:36] "GET /static/beets.css HTTP/1.1" 304 -
10.1.100.167 - - [31/Aug/2023 16:03:36] "GET /static/jquery.js HTTP/1.1" 304 -
10.1.100.167 - - [31/Aug/2023 16:03:36] "GET /static/underscore.js HTTP/1.1" 304 -
10.1.100.167 - - [31/Aug/2023 16:03:36] "GET /static/beets.js HTTP/1.1" 304 -
10.1.100.167 - - [31/Aug/2023 16:03:36] "GET /static/backbone.js HTTP/1.1" 304 -
10.1.100.167 - - [31/Aug/2023 16:03:36] "GET /page/2 HTTP/1.1" 404 -
10.1.100.167 - - [31/Aug/2023 16:03:42] "GET /item/query/a HTTP/1.1" 200 -
[2023-08-31 16:03:49,615] ERROR in app: Exception on /item/331/file [GET]
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/beetsplug/web/__init__.py", line 324, in item_file
    response = flask.send_file(
               ^^^^^^^^^^^^^^^^
TypeError: send_file() got an unexpected keyword argument 'attachment_filename'
10.1.100.167 - - [31/Aug/2023 16:03:49] "GET /item/331/file HTTP/1.1" 500 -
```

**Comment by gwlg-mjh** [comment]
Flask deprecated 'attachment_filename'

https://github.com/beetbox/beets/issues/4818
https://github.com/beetbox/beets/pull/4433

Beets last release was 1.6 and hasn't had a release since the fix was merged so it wouldn't be in lsio 'latest' image I guess, however Nightly still has the issue, shouldn't Nightly be built from beets master rather than installing from pip? Otherwise what's the point?

**Comment by thespad** [comment]
Nightly is installed from the latest master commit https://github.com/linuxserver/docker-beets/blob/nightly/Dockerfile#L88-L92

**Comment by gwlg-mjh** [comment]
Thanks, I was looking at the wrong Dockerfile, however Nightly still seems to have the issue!

I'm running lscr.io/linuxserver/beets:nightly@sha256:f0f6a61cf2e57b1737b3db1bd82c5b0aa4616b9e68d8563161fd118b9be840a3

If I grep /lsiopy/lib/python3.11/site-packages/beetsplug/web/\_\_init\_\_.py it has the wrong code in it.  The correct code seems to be installed at /usr/lib/python3.11/site-packages/beetsplug/web/\_\_init\_\_.py

```
docker run --rm lscr.io/linuxserver/beets:nightly beet --version
beets version 1.6.0
Python version 3.11.5
```

```
docker run --rm lscr.io/linuxserver/beets:nightly cat /lsiopy/lib/python3.11/site-packages/beetsplug/web/__init__.py |  grep \=safe_filename
attachment_filename=safe_filename  <--- Bad
```

```
docker run --rm lscr.io/linuxserver/beets:nightly cat /usr/lib/python3.11/site-packages/beetsplug/web/__init__.py |  grep \=safe_filename
download_name=safe_filename  <--- Good
```

**Comment by thespad** [comment]
Can you please test with `lspipepr/beets:nightly-c15ccb16-pkg-9a6d09b9-dev-5b087bc842a629046d2f51fdd7c31a9404c5dafd-pr-109`

**Comment by gwlg-mjh** [comment]
```
docker run --rm lspipepr/beets:nightly-c15ccb16-pkg-9a6d09b9-dev-5b087bc842a629046d2f51fdd7c31a9404c5dafd-pr-109 cat /lsiopy/lib/python3.11/site-packages/beetsplug/web/__init__.py |  grep \=safe_filename
download_name=safe_filename

docker run --rm lspipepr/beets:nightly-c15ccb16-pkg-9a6d09b9-dev-5b087bc842a629046d2f51fdd7c31a9404c5dafd-pr-109 cat /usr/lib/python3.11/site-packages/beetsplug/web/__init__.py |  grep \=safe_filename
cat: /usr/lib/python3.11/site-packages/beetsplug/web/__init__.py: No such file or directory
```

Beets website also plays correctly now with this image. :thumbsup:

**Comment by djismgaming** [comment]
Seems we need to use the nightly tag for this to work correctly, right?
