### ISSUE TITLE
[BUG] Maintainers did not respond to change request

### ISSUE THREAD

**Issue by RollingStar** [linuxserver/docker-beets#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created an issue https://github.com/linuxserver/docker-beets/issues/94 which received no response. This led me to conclude that this repo is unmaintained and create doc changes to note that LSIO is not maintained by the beets project itself, and some of the default config may differ from what beets ships with.

https://github.com/beetbox/beets/pull/4859

We would love to work with y'all, we don't exactly have the people to dedicate to maintaining e.g. Docker images for beets. But ideally this would look more like a partnership and less like an ivory tower. Is there any way our project can communicate with you?

### Expected Behavior

Open dialogue between LSIO and beets

### Steps To Reproduce

Make an issue, wait for a response

### Environment

```markdown
- OS: github
- How docker service was installed: woo
```

### CPU architecture

x86-64

### Docker creation

```bash
asdf
```

### Container logs

```bash
zxcv
```

**Comment by j0nnymoe** [comment]
Hey,

Apologies for not seeing that original issue. If you're able to come over to our discord discord.gg/linuxserver - ping me when you're in there and we can discuss further =) 

Cheers

**Comment by RollingStar** [comment]
Thanks!
