### ISSUE TITLE
[FEAT] Include originquery plugin

### ISSUE THREAD

**Issue by BGarber42** [linuxserver/docker-beets#118]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Include the beets [originquery](https://github.com/x1ppy/beets-originquery) plugin 

### Reason for change

Improves searching and tagging of music by allowing tags from included files to be searched with

**Comment by aptalca** [comment]
You can install it with https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by BGarber42** [comment]
There's no wheel for it, it's only on github and the container doesn't have the git executable.

**Comment by BGarber42** [comment]
Extensive usage of the universal package install bloats the container image because it installs to non-host mapped directories
