### ISSUE TITLE
[BUG] `beetcamp` Plugin causing nightly builds to install `1.6.0` of beets rather than current upstream. 

### ISSUE THREAD

**Issue by BGarber42** [linuxserver/docker-beets#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Beets `2.0.0` is downgraded to `1.6.0`

### Expected Behavior

Beets `2.0.0` is installed

### Steps To Reproduce

1. Build `nightly` branch

### Environment

```markdown
- OS: Unraid
- How docker service was installed: Distro
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='beets'
  --net='bridge'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="beets"
  -e 'DOCKER_MODS'='linuxserver/mods:universal-package-install'
  -e 'INSTALL_PIP_PACKAGES'='git+https://github.com/x1ppy/beets-originquery|git+https://github.com/x1ppy/gazelle-origin'
  -e 'INSTALL_PACKAGES'='git'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8337]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/beets-logo.png'
  -p '8337:8337/tcp'
  -v '/mnt/user/data/media/':'/music':'rw'
  -v '/mnt/user/data/':'/downloads':'rw'
  -v '/mnt/user/appdata/beets':'/config':'rw' 'lscr.io/linuxserver/beets:nightly'
```

### Container logs

```bash
https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-beets/detail/nightly/1390/pipeline/155/#step-166-log-734
```

Upstream package reqs: https://github.com/snejus/beetcamp/blob/main/pyproject.toml#L30

**Comment by thespad** [comment]
I suspect this doesn't happen with the stable build because we install beets==2.0.0 with the same pip command as beetcamp and so it finds an older version of beetcamp that's compatible
```
#10 33.37 INFO: pip is looking at multiple versions of beetcamp to determine which version is compatible with other requirements. This could take a while.
#10 33.37 Collecting beetcamp
#10 33.50   Downloading beetcamp-0.19.2-py3-none-any.whl.metadata (15 kB)
```
Whereas with nightly we build beets from source, then install beetcamp afterwards.

We could remove it entirely, or we could pin it to 0.19.2 until upstream is fixed, which might be preferable.

**Comment by thespad** [comment]
Pushed a new build with beetcamp pinned to the previous version so it won't try and force an old beets install. Will revisit once beetcamp fix their requirements.
