### ISSUE TITLE
Another request: Add ImageMagick to list of default packages

### ISSUE THREAD

**Issue by dprus** [linuxserver/docker-beets#2]
The minwidth feature of the fetchart plug-in in beets requires ImageMagick in order to parse the images.

I installed it from the default repos with 'apt-get install imagemagick' and the minwidth feature started working.

**Comment by dprus** [comment]
By the way, you may want to install imagemagick with the --no-install-recommends option. Otherwise Ubuntu installs a bunch of stuff that beets doesn't appear to need. The amount of space taken up goes from over 60mb to just over 14.

**Comment by smdion** [comment]
I'll test it out an commit if it looks good!

**Comment by sparklyballs** [comment]
i looked at this earlier, unless we add it as a separate install with it's own apt-get line, adding --no-install-recommends will affect all packages we're installing.

installing imagemagick with recommended packages results in an 800mb + image.

**Comment by sparklyballs** [comment]
adding the required dependencies and install it via pip, pillow adds only 15mb to the image size, satisifies the needs of the plugin mentioned and negates the need for a separate apt-get install line.
