### ISSUE TITLE
sypervisor log shows lots of errors about 'web' command...

### ISSUE THREAD

**Issue by dprus** [linuxserver/docker-beets#3]
I see this over and over again in the supervisor log: error: unknown command: 'web'

**Comment by smdion** [comment]
I'll check it out.

**Comment by Joshfindit** [comment]
May be a generally resolved issue, but I ran across it.

Here's my rundown:

1. Created a container with a backup of my main config/db
2. Got `error: unknown command 'web'`
3. Jumped in to bash in the container, tested `beet web` (Same error of course)
4. Realized that the web plugin has to be enabled ( http://beets.readthedocs.io/en/v1.4.2/plugins/index.html )
5. Added `web` to the the plugin list
