### ISSUE TITLE
Add Requests Package to Dockerfile

### ISSUE THREAD

**Issue by bigsing** [linuxserver/docker-beets#32]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
The PlexUpdate plugin requires the requests package be installed via pip. Could this possibly be added to the dockerfile?

PlexUpdate Plugin: [http://beets.readthedocs.io/en/v1.4.7/plugins/plexupdate.html](url)

**Comment by IronicBadger** [comment]
How would you feel about submitting a pull request for this?

**Comment by thetarkus** [comment]
The `requests` package is pulled in as a dependency for another library, so the `PlexUpdate` plugin will work. Although it probably should be added to the Dockerfile.

During pip install section of script:
```sh
Installing collected packages: beautifulsoup4, six, mutagen, munkres, unidecode, musicbrainzngs, pyyaml, jellyfish, enum34, beets, beets-copyartifacts, chardet, urllib3, certifi, idna, **requests**, oauthlib, discogs-client, itsdangerous, MarkupSafe, Jinja2,
Werkzeug, click, flask, pillow, pip, audioread, pyacoustid, pylast
```
