### ISSUE TITLE
Ram fills when chroma plugin is active

### ISSUE THREAD

**Issue by enricosan** [linuxserver/docker-beets#38]
I posted about the issue here: https://groups.google.com/forum/#!topic/beets-users/rQgK1l4mIrI

Basically the ram fills when the chroma plugin is active, it doesn't fill when it's not active. Ram continues filling until beets stalls, if left for long enough all docker containers and even the unraid docker UI slows to a crawl and slowly becomes unresponsive, takes about 30mins. Ram fills to about 27GB (out of 32GB on the system) before locking up. Ram is cleared when import is cancelled or beets is restarted.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

UNRAID 6.5.3

M/B: Supermicro - X9SRL-F
CPU: Intel® Xeon® CPU E5-1650 v2 @ 3.50GHz
HVM: Enabled
IOMMU: Enabled
Cache: 384 kB, 1536 kB, 12288 kB
Memory: 32 GB Multi-bit ECC (max. installable capacity 512 GB)
Network: eth0: 1000 Mb/s, full duplex, mtu 1500 
 eth1: not connected
Kernel: Linux 4.14.49-unRAID x86_64
OpenSSL: 1.0.2o

<img width="1196" alt="screen shot 2018-08-24 at 9 16 54 am" src="https://user-images.githubusercontent.com/89800/44556740-7d050900-a77e-11e8-8abe-5f4925146ebb.png">

**Comment by jmccoy555** [comment]
Same issue here unfortunately. Disabling the chroma plugin and it works fine.

**Comment by homerr** [comment]
I'm afraid this looks like it is more of an issue with the plugin than anything we're able to help with. You may find it useful to approach the developer of it, referencing this issue.

**Comment by hpz937** [comment]
I am experiencing this as well. There is an open issue for this on beets github https://github.com/beetbox/beets/issues/3082 
While I get this is an issue with the developer of the plugin, I feel it should be disabled by default in the linuxserver docker image until it is fixed.
