### ISSUE TITLE
make cron-file persistent?

### ISSUE THREAD

**Issue by Hobbabobba** [linuxserver/docker-beets#39]
beets can use `cron`-jobs to check for new songs in the downloads-directory and it works fantastic to autoimport new music.
but whenever i restart the container, the `cronfile` will reset. is it possible to make the `cronfile` persistent?

**Comment by ombre8** [comment]
just use `-v /path/to/cronjob:/etc/periodic/hourly/`

**Comment by homerr** [comment]
As advised above, this would be the best way to achieve this as you can cron what you want/how you want it.
