### ISSUE TITLE
BPD plugin needs access to sound devices

### ISSUE THREAD

**Issue by Spass1966** [linuxserver/docker-beets#40]
The BPD plugin is included in this container but has no way of processing audio out, making it impossible to stream music from. Is it possible to make the BPD plugin functional using the current container?

See post here on the Beets forum for more context: https://discourse.beets.io/t/how-do-i-use-the-brd-plugin-to-play-music-from-my-server/593

**Comment by tobbenb** [comment]
Looking at the plugin page, it's just a mpd compatible server. To play something on a mpd client, alsa isn't needed. The only requirement mentioned in the plugin Readme is gstreamer.
So it doesn't need access to the soundcard. 

I'll take a look in the weekend and see if it's possible to get it installed.

**Comment by taohansen** [comment]
Just checking in. How's it going?

**Comment by thelamer** [comment]
Given that thread and your own research it sounds like you would need to do a device mount for your sound device and we would need to install the a linux sound subsystem to interact with it. 
Have you tested mounting the sound device using the --device variable and using apk commands in the container to install the needed software? 
If you have a working example that would be easier to determine what we can add and the functionality it achieves. 
https://wiki.alpinelinux.org/wiki/PulseAudio
https://wiki.alpinelinux.org/wiki/Sound_Setup

**Comment by thelamer** [comment]
As it has been more than a month, I am going to close this issue. Please open a new one if you determine how to interact with your system devices from Docker: 

https://docs.docker.com/engine/reference/commandline/run/#add-host-device-to-container---device
