### ISSUE TITLE
Adding support for Gmusic plugin

### ISSUE THREAD

**Issue by shuaiscott** [linuxserver/docker-beets#41]
Feature request to add container support of gmusic plugin

Add apks:

- libc-dev
- libxml2-dev
- python-dev
- xmlsec-dev

Add python library

- gmusicapi

(I can probably get to this in a day or so and submit a pull request)

**Comment by thelamer** [comment]
In the current image with python3 this plugin is no longer functional, we will not be adding it to our base image.
