### ISSUE TITLE
Is lyrics plugn included?

### ISSUE THREAD

**Issue by Spass1966** [linuxserver/docker-beets#53]
I did a search of the repo but nothing came up. If not, this is a request to include.

**Comment by sparklyballs** [comment]
everything other than langdetect for on the fly translations of lyrics is already in this image. 

enable lyrics by following the docs here and editing the config file in the volume mount. 

https://beets.readthedocs.io/en/v1.4.7/plugins/lyrics.html

**Comment by alexindigo** [comment]
@sparklyballs looks like bandcamp isn't included:

```
** error loading plugin bandcamp:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.bandcamp'
```
