### ISSUE TITLE
[Question] nightly tag on docker hub

### ISSUE THREAD

**Issue by kimpenhaus** [linuxserver/docker-beets#54]
Hi all,

I came across the beets docker image and saw on docker hub that the `nightly` tag is about a month old.

<img width="368" alt="Bildschirmfoto 2019-05-03 um 22 24 48" src="https://user-images.githubusercontent.com/575109/57163719-4940af80-6df2-11e9-8bb2-ae8a07d854a1.png">

Not sure if my understanding is wrong, but shouldn't that image been updated `nightly`? I just double checked if there weren't any code changes on the beets repro but the latest head version of beets is just 1 day old.

<img width="239" alt="Bildschirmfoto 2019-05-03 um 22 26 18" src="https://user-images.githubusercontent.com/575109/57163803-7ee59880-6df2-11e9-9b60-80427d4ad56d.png">

So I assume it is outdated? Or is there any different mechanism to get it updated. My goal was to run watchtower to updated daily to the latest head.

Thanks for all the effort you did with all the images!
m.

**Comment by thelamer** [comment]
You are correct in the mayhem we missed the triggers for this branch, will set these up today.

**Comment by kimpenhaus** [comment]
\m/ thanks mate!

**Comment by thelamer** [comment]
Building now and will trigger on external commits to their master branch: 
https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-beets/branches
