### ISSUE TITLE
Question: Why is it necessary to run the image as service for beet web?

### ISSUE THREAD

**Issue by sandreas** [linuxserver/docker-beets#56]
At first i would like to thank you for this great piece of work... it saved me a lot of time.

One thing does not fit my needs and i just would like to know, if there is a reason, using `beet web` via custom shell script by default?

I personally don't like the web interface at all, I'm using `beet` only to organize music.

So unfortunately this image is not usable for me - my solution was to create a Dockerfile based on yours without the beet web initialisation script... an example:

```
# Dockerfile
# ...everything exactly like in your Dockerfile
 rm -rf \
	/root/.cache \
	/tmp/*

# environment settings
ENV BEETSDIR="/config" \
EDITOR="nano" \
HOME="/config"

# HERES THE CHANGE
CMD ["web"] # i would prefer ["help"], but not if default mode should be the web interface...
ENTRYPOINT ["beet"]
```

```
# building the image as *beets*
docker build . -t beets
```

```
# Adding some aliases to my shell...
alias beet='docker run -it --rm -u $(id -u):$(id -g) -v "${HOME}/docker-data/beets:/config" -v "${HOME}/dotfiles/etc/beets/config.yaml:/config/config.yaml:ro" -v "${HOME}/music:/music" -v "${HOME}/incoming-music:/downloads" beets'

alias beet-import='beet import /downloads'
```

Now the default command is `beet web`, but all other commands could be used without having to run a service and an open port too, e.g. `beet ls`.

What do you think about it? Could this be an improvement or would it break something important?

**Comment by thelamer** [comment]
This container provides the beets web interface, that is what it does. 
If you are happy with the functionality of your forked version I fully support you to continue using it with a new entrypoint etc. 
We will not be making the above changes to this container and I am closing this issue.

**Comment by sandreas** [comment]
Mmh I'm a bit unhappy with this answer, because I did not want to make you change the image but understand the WHY you did not choose an entry point, since i learned a lot of your Dockerfile and perhaps there is a lot more to learn - i provide a similar image in one of my open source projects.

Anyway, thanks for the quick response.

**Comment by sparklyballs** [comment]
you can override/add any entrypoint at run time with --entrypoint=somecommand 

the docker will likely not stay running but you can start it as part of your alias if that is the case.

**Comment by sandreas** [comment]
@sparklyballs 
Thank you... I maybe wrong, but in my opinion i can't override this part without a fork or extending dockerfile, can I?:

```
# copy local files
COPY root/ /
```

Due to the startup script `root/etc/cont-init.d/30-config` and the service `root/etc/services.d/beets/run` the config is always `chown`ed  for user:group `abc:abc` and `beet web` is always started, no matter what command line parameters are used to run or build the image...  

I would have liked to have understood the reasons for *this* instead of leaving out the 
```
chown -R abc:abc \
	/config
```
and
```
exec \
	s6-setuidgid abc beet web
```

part of the scripts in favour of 

```
CMD ["web"]
ENTRYPOINT ["beet"]
```

to keep it more *overridable* and not forcing the user to be `abc`.  I'm sure there are reasons, but with my limited docker knowledge, I did not get it ;-) 

Nevermind, keep up the good work. I'll fork this thing later.
