### ISSUE TITLE
Cannot calculate replaygain for OPUS format, need: bs1770gain

### ISSUE THREAD

**Issue by RandomNinjaAtk** [linuxserver/docker-beets#62]
When using the replaygain plugin for beets on opus (.opus) files, you get the following error

"error: replaygain initialization failed: Is bs1770gain installed? Is your method in config correct?"

Docker Host OS: Unraid

**Comment by thelamer** [comment]
We do not install bs1770gain, I think this would need to be built from source.
I am not the maintainer of this repo, but I have been told that supporting plugins is tough as essentially everyone has a must work plugin and the deps are all over the place. 

I would really like if a power user could pick up and build a "heavy" modification layer for this image that installs tons of deps on top of our base image. 
https://github.com/linuxserver/docker-mods

**Comment by samuelnilsson** [comment]
> 
> 
> When using the replaygain plugin for beets on opus (.opus) files, you get the following error
> 
> "error: replaygain initialization failed: Is bs1770gain installed? Is your method in config correct?"
> 
> Docker Host OS: Unraid

Just a tip. In the latest nightly of beets there is an ffmpeg backend for the replaygain plugin which can calculate r128 replaygain tags. bs1770gain will most probably be removed from beets due to associations with white nationalism (see https://github.com/beetbox/beets/issues/3127).
