### ISSUE TITLE
Beets imported files owned by root:root

### ISSUE THREAD

**Issue by undaunt** [linuxserver/docker-beets#68]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
Running a beets import with either copy or move, files copied from the completed music download folder to the local library folder should be owned by the user ID and group ID specified as PUID and PGID in the docker environment. On my system, this is PUID 1000 and PGID 999.

## Current Behavior
After running a beets import `docker exec -ti beets /bin/bash -c 'beet import /downloads'` or `docker exec -ti beets /bin/bash -c 'beet import -c /downloads'` the files that appear in the /music path (on host, at /home/data/music/) appear owned by root:root instead of myuserid:docker. The files in downloads are already properly owned as myuserid:docker, as they appear there from Lidarr.

## Steps to Reproduce
1. Configure beets docker-compose and config.yaml.
2. Run import (docker exec -ti beets /bin/bash -c 'beet import /downloads')
3. ls -ahl on files to verify.

## Environment
**OS:**  Ubuntu 18.04 server
**CPU architecture:** x86_64      
**How docker service was installed:**   
```
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get install -y docker-ce
sudo systemctl status docker
sudo usermod -aG docker ${USER}

VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | jq .name -r)

DESTINATION=/usr/local/bin/docker-compose
sudo curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m) -o $DESTINATION
sudo chmod 755 $DESTINATION
sudo chmod +x $DESTINATION

sudo setfacl -Rdm g:docker:rwx ~/docker
sudo chmod -R 775 ~/docker
```

## Command used to create docker container (run/create/compose/screenshot)
```
  beets:
    image: linuxserver/beets
    container_name: beets
    restart: unless-stopped
    networks:
      - web
    depends_on:
      - musicbrainz
    volumes:
      - ${USERDIR}/docker/beets/config:/config
      - /home/gmedia/music:/music
      - /home/data/downloads/complete/music:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
```

/home/gmedia is a mergerfs mount, rw local & ro gdrive with an rclone backend mount of /home/data (local) and /home/gdrive (remote)

I'm not exposing the web interface via traefik so I've removed all traefik labels from my normal compose template as well as the expose/port values.

## Docker logs
```
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    999
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
 * Serving Flask app "beetsplug.web" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8337/ (Press CTRL+C to quit)
```

**Comment by tobbenb** [comment]
You have to add the -u abc to the docker exec command. With the command you used, you are running the command inside the container as root and the files will end up being owned by root.

**Comment by undaunt** [comment]
@tobbenb Thanks - didn't realize I had to do that! So essentially the container is passing my id, but defaults to root without that in the command.

Guess I never learned that prior as most of the other containers are GUI and didn't crop up for me.

In any case, thanks again.

**Comment by tobbenb** [comment]
Docker defaults to the root user if you don't specify a user when you exec into the container.

There is always something to learn :)
