### ISSUE TITLE
Remove downloads and music volumes from Dockerfile

### ISSUE THREAD

**Issue by artbird309** [linuxserver/docker-beets#75]
Can the extra volumes (/downloads /music) be removed from the docker files so the user can decide how they want to setup the filesystem like they did in Sonarr?

Reference:
https://github.com/linuxserver/docker-sonarr/pull/133

Files to change:
https://github.com/linuxserver/docker-beets/blob/621d86303e34dbb82eaadc4c40a2f6ce1c16609a/Dockerfile#L115
https://github.com/linuxserver/docker-beets/blob/621d86303e34dbb82eaadc4c40a2f6ce1c16609a/Dockerfile.aarch64#L115
https://github.com/linuxserver/docker-beets/blob/621d86303e34dbb82eaadc4c40a2f6ce1c16609a/Dockerfile.armhf#L115

**Comment by tobbenb** [comment]
There is nothing stopping anyone from using the folder setup they want. All the defined volumes does is create the volume if a folder from host is not volume binded.

We are removing the defined volumes when we update the dockerfile, and of course remembers it, so empty volumes are not created.
