### ISSUE TITLE
Update to python 3.8.10 breaks image on Raspberry Pi

### ISSUE THREAD

**Issue by jreedsellers** [linuxserver/docker-beets#80]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Container should serve beets.

## Current Behavior

Logs show it's hung on "ValueError: Name node can't be used with 'None' constant"
Running v1.4.9-ls49 works fine.

## Steps to Reproduce

1. Start container in Docker with latest image using docker-compose

## Environment
**OS:** Raspbian
**CPU architecture:** arm32
**How docker service was installed:** Official docker repo

## Command used to create docker container (run/create/compose/screenshot)

  beets:
    image: linuxserver/beets:latest
    container_name: beets
    restart: unless-stopped
    ports:
      - 8337:8337
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/XXX
      - UMASK=002
    volumes:
      - /beets/config:/config
      - /beets/music:/music
      - /beets/downloads:/downloads

## Docker logs

ValueError: Name node can't be used with 'None' constant,
Traceback (most recent call last):,
  File "/usr/bin/beet", line 33, in <module>,
    sys.exit(load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()),
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main,
    _raw_main(args),
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main,
    subcommands, plugins, lib = _setup(options, lib),
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup,
    lib = _open_library(config),
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library,
    get_path_formats(),,
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats,
    path_formats.append((query, template(view.as_str()))),
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template,
    return Template(fmt),
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__,
    self.compiled = self.translate(),
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate,
    func = compile_func(,
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func,
    prog = compile(mod, '<generated>', 'exec'),
ValueError: Name node can't be used with 'None' constant,

**Comment by aptalca** [comment]
Seems to be an upstream issue: https://github.com/beetbox/beets/issues/3674

**Comment by patsaindon** [comment]
Same issue here

**Comment by Bidley** [comment]
Same issue here (OMV x86)

**Comment by jsetton** [comment]
It looks like the main issue is that the last `beets` released version [`1.4.9`](https://github.com/beetbox/beets/releases/tag/v1.4.9) was back in 2019.

Using the `master` branch version resolves this issue. So maybe this project could track that branch instead of releases.

Anyway, in the meantime, adding the below shell script to `/config/custom-cont-init.d/50-install` can be used as a workaround to update the container beets package to the latest version on startup.

```sh
#!/usr/bin/with-contenv bash

# Install latest beets version
#  https://github.com/linuxserver/docker-beets/issues/80
pip3 install -q --no-cache-dir https://github.com/beetbox/beets/zipball/master
```

**Comment by Bidley** [comment]
Thanks @jsetton that worked a treat.

**Comment by aptalca** [comment]
No need for that: https://github.com/linuxserver/docker-beets#version-tags

**Comment by Taubin** [comment]
Switching to nightly got things working for me again. Cheers.

**Comment by jsetton** [comment]
@aptalca good point although I just tried the `nightly` image and it is missing `beet-extrafiles` and `mp3val`. It looks some of the addition to the `master` image weren't ported over.

**Comment by aptalca** [comment]
blame yourself for that :-P https://github.com/linuxserver/docker-beets/pull/55
you only PRed it to master lol

**Comment by aptalca** [comment]
if you want to PR to nightly builds, it's just the nightly branch here

**Comment by jsetton** [comment]
@aptalca I know 😄 Only for half of it though.

`beets-extrafiles`: #47

**Comment by jsetton** [comment]
@aptalca I submitted PR #81 against the nightly branch to add the missing changes for your review.

**Comment by quamok** [comment]
switching to nightly fixes the python error, but replaygain with GStreamer as backend isn't working though.

**Comment by jsetton** [comment]
It looks like the GStream related packages were somehow [removed](https://github.com/linuxserver/docker-beets/commit/6bce4e841d167bf17c39eed772745434b3378c19#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L33-L34) when the `nightly` branch was initially created.

The following packages need to be added back to that branch:

```
gst-plugins-good
gstreamer
py3-gobject3
```
