### ISSUE TITLE
Upgrade python 3.8 to 3.9?

### ISSUE THREAD

**Issue by DOFfactory** [linuxserver/docker-beets#84]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

There are some beets plugins that are broken in the current python v3.8. It has been reported that there are some fixes with the latest python 3.9. Would it be please upgrade it to the latest version?

**Comment by mclare** [comment]
Currently getting a "ValueError: Name node can't be used with 'None' constant" error when I run beet stats and other commands. I'll be watching the outcome of this issue to see if I should roll back or start auditing plugins. This is also my chance to say thanks to those maintaining this.

**Comment by aptalca** [comment]
@DOFfactory no python 3.9 in the alpine repo

@mclare see #80

**Comment by mclare** [comment]
@aptalca Thanks!

**Comment by DOFfactory** [comment]
Actually, we do not need upgrading to python3.9 but rather downgrading to python3.7, see here: https://github.com/beetbox/beets/issues/3975
