### ISSUE TITLE
Add direct link to this Source Repository on https://hub.docker.com/r/linuxserver/beets/

### ISSUE THREAD

**Issue by gritstub** [linuxserver/docker-beets#89]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
On the right side of the [Docker Hub page](https://hub.docker.com/r/linuxserver/beets/) underneath the "Docker Pull Command", add a link to this "Source Repository".  I have seen this on other linuxserver.io Docker Hub pages, and find it very useful.

## Current Behavior
No link to this Source Repository

**Comment by aptalca** [comment]
We have no control over it. Docker hub manages that link and only displays it if the images are built by docker hub. Our images are built by our Jenkins CI: https://ci.linuxserver.io

The repos that have the link _used_ to use docker hub to build the images a long time ago (many years).

**Comment by gritstub** [comment]
Understood. Thanks!

**Comment by gritstub** [comment]
@Roxedus : Thank you. I missed that this header was a link.
