### ISSUE TITLE
[BUG] Replaygain bug (#20) seems to be back

### ISSUE THREAD

**Issue by bossanova808** [linuxserver/docker-beets#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On updating to the latest beets image, I received:

`error: replaygain initialization failed: Failed to load GStreamer: python-gi not found`

#20 - seems this bug is back with the rebase to Alpine?

### Expected Behavior

That error wouldn't be there.

### Steps To Reproduce

1. Docker running on Ubuntu 22.04.02 LTS
2. Pull the latest beets image
3. with this in your config:

```
replaygain:
    backend: gstreamer
    overwrite: no  
```

You get:

`error: replaygain initialization failed: Failed to load GStreamer: python-gi not found`

### Environment

```markdown
- OS: Ubuntu 22.04.02 LTS
- How docker service was installed: distro's package manager
```

### CPU architecture

x86-64

### Docker creation

```bash
beets:
        image: ghcr.io/linuxserver/beets:nightly
        container_name: beets
        environment:
            - PUID=${UID}
            - PGID=${GUID}
            - TZ=${TZ}
        volumes:
            - ${BEETS_CONFIG}:/config
            - ${BEETS_OUT_KAMY}:/music
            - ${BEETS_IN}:/downloads
        ports:
            - 8337:8337
        restart: unless-stopped
```
```


### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
error: replaygain initialization failed: Failed to load GStreamer: python-gi not found
error: replaygain initialization failed: Failed to load GStreamer: python-gi not found
error: replaygain initialization failed: Failed to load GStreamer: python-gi not found
error: replaygain initialization failed: Failed to load GStreamer: python-gi not found
```
...and that error just repeats on endlessly
```

**Comment by thespad** [comment]
With the most recent changes we switched to installing all the python packages via pip as the previous mix of pip and repo package manager is something python are pushing people away from.

It looks like we may have missed a package that was coming in as part of another, will need a little digging as I thought we'd got everything.

**Comment by bossanova808** [comment]
Thanks for looking at it!

**Comment by thespad** [comment]
PR's merged, next build will include the fix.
